### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by kayz1** [jon-hall/pm2-windows-service#15]
Awesome job so far!

A few features that I would like to see included:
1. Service description (e.g. -n ServiceName -d Service Description)
2. Clean Environment variables on uninstall (PM2_HOME, PM2_SERVICE_SCRIPTS... and SET_PM2_SERVICE_SCRIPTS...)
3. Setup service from configuration file (-r) // create service from batch file

**Comment by jon-hall** [comment]
Hi, sorry it took me so long to get back to you - thanks for the feedback though; I think they're all great ideas that I'll try and put in as soon as I get a chance.

The service description I'll have to look into whether the libraries this uses support that, but shouldn't be difficult if they do.

Adding a prompt/flag to the uninstall to do environment clean-up is also something I should have put in when I started dirtying the environment with the setup prompts, so I'll make sure this gets in to the next release.

The configuration from file is already done on the `config-rc` branch, and uses `rc` for handling  configuration from a file for automated setups - this should also be making out into the next release.

Thanks again for the feedback and I'll keep this issue updated as features get implemented/released.

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
