### ISSUE TITLE
Error: Unable to load PM2 JSON configuration file

### ISSUE THREAD

**Issue by ClintSchauff** [jon-hall/pm2-windows-service#30]
Hi Jon,

I'm trying to start PM2 as a service using a file called process.json with the following parameters:

{
  "apps" : [{
    name      : "myapp",
    script    : 'c:\\myApp\\server.js',         // Script to be run
    exec_mode : 'cluster',        // Allow your app to be clustered
    instances : 1,                // Optional: Scale your app by 4
    args      : "Node1",
    max_memory_restart : '100M'   // Opt
  }]
}

It works fine running PM2 in command line and creates the service just fine but when I try to start the service, I keep getting the above error in the logs.  The env vars are all set a machine level.  Here is how I set it up:

![image](https://user-images.githubusercontent.com/32966912/31838264-9ecb830e-b5a1-11e7-9c39-001f34932316.png)

I also tried setting the PM2_SERVICE_SCRIPTS var with process.json in the path, but I get the same error.

Any thoughts?

Thanks, Clint

**Comment by jon-hall** [comment]
Hi Clint, thanks for providing so much detail with the issue, I think I've managed to spot the problem in the info you provided.

It looks like the cause of this error is the config that you're using is json5, but this package [just uses `require` to load the JSON config file](https://github.com/jon-hall/pm2-windows-service/blob/29d803cb9258c12b3f5fb90bd7e916cb374baffc/src/service.js#L60), and that'll only handle plain old JSON.

When I changed my local version of the config to:
```
{
    "apps" : [{
        "name" : "hello-world",
        "script" : "index.js",
        "exec_mode" : "cluster",
        "instances" : 1,
        "args" : "Node1",
        "max_memory_restart" : "100M"
    }]
}
```
The service is then able to start and works as expected.

It looks like [pm2 does support json5](https://github.com/Unitech/pm2/issues/1296), even though [the docs don't exactly make it clear](http://pm2.keymetrics.io/docs/usage/application-declaration/#json-format) - I'll look into adding support for loading json5 config files to this package, but reverting to regular JSON should get the service running for you in the meantime.

Let me know if you're still getting issues with keeping the service running.

**Comment by ClintSchauff** [comment]
Hey Jon,

Thanks for the quick response!  I spent 8 hours yesterday trying to figure out why that wouldn't work and didn't notice it.  That worked like a champ.  Thanks again!

Clint

**Comment by ClintSchauff** [comment]
Hi Jon,

Thanks for all of your help!  That did indeed fix my issue.  I have another question for you if you don’t mind.  I want to run 2 separate apps with 2 separate services but I haven’t been able to get that to work.  The only way I’ve been able to get it to work is if I create a config file that starts 2 apps and then run it with a single service.

Here is how I’ve tried it:  

1.	 Start and save the first app in PM2.
2.	Create the service.
This all seems to work great.
 

![image](https://user-images.githubusercontent.com/32966912/32290673-cf5c5b72-bf08-11e7-9b2d-27fd53930c97.png)



Now to start my other app:

1.	 switch to the c:\myApp directory
2.	Start process.json (config file for myApp)
3.	Pm2 save
4.	Create the service with a new service name (myApp)
 
![image](https://user-images.githubusercontent.com/32966912/32290680-d59f1b96-bf08-11e7-9f2f-be29cd1d9e54.png)

This seems to work…except that once I stop the services, run PM2 Kill and try to use the services to start the apps again, the apps don’t start.  There are no errors, the services are running but the apps simply haven’t started:

 
![image](https://user-images.githubusercontent.com/32966912/32290690-d9a59350-bf08-11e7-818d-07c9082384f7.png)


Is it possible to create 2 separate services for 2 separate apps?

CS
