### ISSUE TITLE
Question: Can we add arguments for pm2 processes?

### ISSUE THREAD

**Issue by hurricane766** [jon-hall/pm2-windows-service#34]
Hi,
I'm wondering how I can set things up so that the pm2 process starts with arguments like --max-restarts=10 or --name=development ?

Thanks

**Comment by jon-hall** [comment]
Hi, there's two ways you can achieve this I think:

#### pm2_dump
- Make sure `%PM2_SERVICE_SCRIPTS%` is not set in your environment (restart your machine if you have to clear it)
- Make sure the service is already running
- `pm2 start` the set of processes you want to be automatically launched by the service - supply whatever arguments you want at this point (e.g. `pm2 start index.js --name development`)
- `pm2 delete` any currently managed processes you don't want the service to restart every time it loads
- `pm2 dump` (or `pm2 save`) will then dump the list of processes `pm2` is currently running, including their arguments
- Next time the service restarts it'll `pm2 resurrect` that set of processes as you configured them

#### process files
- Create a process file (or files) for your app (or apps), [as described here](http://pm2.keymetrics.io/docs/usage/application-declaration/)
- This process file can include lots of configuration for how to run your application - see the docs
- Make sure `%PM2_SERVICE_SCRIPTS%` **is set** in your environment (restart your machine if you have to set it), and point it to the process file (or files, using a semi-colon separated string) created for your app(s)
- Next time the service is restarted it should boot the application(s) specified in the process file(s) in `%PM2_SERVICE_SCRIPTS%`, complete with any configured options

Either of those should do the job, let me know if you get any issues with getting it working.

**Comment by hurricane766** [comment]
Thanks, I didn't know about the process files, that seems like the easiest way to go.
