### ISSUE TITLE
Script args not passed with service start

### ISSUE THREAD

**Issue by T-Hugs** [jon-hall/pm2-windows-service#35]
I launch an app in pm2 with `pm2 start index.js -- --some-argument`. When I type `pm2 show index` it lists `script args  │ --some-argument`. I `pm2 save` this, and when I `resurrect`, it correctly passes those args.

But when I install the service, the `--some-argument` does not get passed to index.js (and `pm2 show index` shows "N/A" for script args). Is there any way to ensure these args are passed to app when the service starts?

**Comment by jon-hall** [comment]
Hi, sorry this isn't working for you; I checked this on my setup by doing the following:

- Make sure `PM2_SERVICE_SCRIPTS` is not set in the machine environment
- Make sure `PM2_HOME` is set at machine-level and points to a directory that the service user (LOCAL SYSTEM) can write to
- Make sure `PM2_HOME` is not being shadowed by a duplicate user-level environment variable
- Launch the service to make sure the service daemon is running
- Run `pm2 status` from an administrative prompt to check what apps are already running (all the subsequent commands were also run from admin cmd prompts)
- Launch a test app with `pm2 start index.js -- --some-argument` (this app is just a http server which responds with `JSON.stringify(process.argv)`)
- Check it's running with `pm2 status`, check the args being passed through with `pm2 show <id>`
- Everything looked fine
- Run `pm2 save` to save the current set of pm2 processes (the directory it saves to should be within the machine-level `PM2_HOME` folder)
- Stop the service
- Run `pm2 status` again, this time it spawns a new daemon (the service one is dead) and has no processes running
- Run `pm2 kill` to get rid of the non-service daemon
- Start the service again
- Run `pm2 status` - this shows the processes I'd previously had pm2 launching, as well as the new process that I launched with `--some-argument`
- Run `pm2 show <id>` to check the args for the test process
- The `--some-argument` arg is still being passed in after re-launching the service
- Visiting the test app in a browser also prints out `--some-argument`, confirming that it is being passed to the app

It looks like this *should* be working for you, so there must be some problem with your setup that's causing it to fail.

The key things to check are:

- The environment variable setup (you need `PM2_HOME` setup at machine level but must not have `PM2_SERVICE_SCRIPTS` [or similar] set)
- Make sure that the service is responsible for initialising the daemon you're interacting with (stop service, `pm2 kill`, start service can do this)
- Use an admin prompt, again to make sure you're interacting with the service daemon
- Verify the location `pm2 save` is writing to
- Check the various logs (app logs, pm2 process logs, pm2 logs, and pm2 service logs) to see if they reveal anything interesting

If none of the above are resolving the issue then just let me know and I'll try and debug further.  If you can include some system info (windows/node/pm2 versions etc.), (sanitised) environment setup, and/or logs would be very handy for this.
