### ISSUE TITLE
Add more information when finding a error to load the files in PM2_SERVICE_SCRIPTS

### ISSUE THREAD

**Issue by canesqui** [jon-hall/pm2-windows-service#38]
Adding additional information beyond the generic error "Unable to load PM2 JSON configuration file x" will help users to debug configuration errors quicker, as the one mentioned in issue #30.

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
