### ISSUE TITLE
Support different versions of global pm2

### ISSUE THREAD

**Issue by jon-hall** [jon-hall/pm2-windows-service#4]
Currently the pm2 CLI starts emitting warning messages when the plugin version and the globally installed versions differ, there should be an easy way to tell pm2-windows-service what version of pm2 you want it to use.

**Comment by NeilCresswell** [comment]
Also have this issue. If it's helpful the two versions I'm seeing are v1.0.0 and v0.15.10.

I'd previously globally installed the latest PM2 first before finding your awesome tool, and was glad to find it resolved my task scheduling problems on a Windows 2012 R2 64 server. Yay, and thank you!

**Comment by jon-hall** [comment]
Sorry I didn't get back to you sooner on this, glad to hear the package was useful for you :smile:. I've just pushed something up which changes the service so it tries to find your global pm2 install and use it, instead of its own copy, whenever possible.

It also supports specifying where it should look for pm2 using the `PM2_SERVICE_PM2_DIR` environment variable - this should be set to a folder containing `node_modules/pm2/`.

The same issues as mentioned in the caveats apply - so, if you opt to let it find the global install, it'll be the global install of `pm2` for the user the service runs as that gets used.

I currently seem to have issues with running this against a global `pm2@1.0` that I need to investigate further, so I wouldn't consider this patch stable just yet - I'll be digging into it a bit more in the next couple of days.

**Comment by mountaindude** [comment]
@jon-hall:
Tried getting the global PM2 config working, no luck against pm2@1.1.3. 
Did you make any progress on solving the issues you mentioned above?

**Comment by jon-hall** [comment]
Apologies in the delay on replying, regrettably, I hadn't looked at this beyond the patch I mentioned above - there'd been no movement on the issue so I neglected to look into it any further.  It'll probably be the weekend before I have enough time to really dig into this, but given it's a definite issue that is long overdue I'll make sure I do set aside some time and hopefully get this solved.  Thanks for bringing this back to my attention :).

**Comment by jon-hall** [comment]
Took another look into this and I'd made an error when using the `PM2_SERVICE_PM2_DIR` environment variable which would have caused it to fail.  I've pushed a fix for this and it now appears to work correctly when utilising the global pm2 version (tested on Win 10, using `0.15.x` local pm2 and `1.0.0` global).

If you can uninstall the current service (`pm2-service-uninstall`), install the latest master (`npm install jon-hall/pm2-windows-service -g`), make sure you have the path to the pm2 folder you wish to use set in the `PM2_SERVICE_PM2_DIR` machine-level environment variable, and give it another go.  Please let me know if it still isn't working for you, if you can also post up the contents of the daemon logs they might help identify the issue (you'll find them in the pm2-windows-service install folder, in `src/daemon`).

**Comment by s-a** [comment]
Is it not obsolete since we are able to use global installed pm2?

**Comment by jon-hall** [comment]
The PR from s-a (#10) fixed this, since we now don't use a local version.
