### ISSUE TITLE
App failing to launch

### ISSUE THREAD

**Issue by DaveMacNeil** [jon-hall/pm2-windows-service#42]
Hello,

I made a service for testing, and it worked with no issue. I later ran the uninstall service command. Afterwards, I created a service again, but creating the service closed my apps (main + worker). I started them manually and ran `pm2 save`, which said it saved successfully, but I get this error

```
[2018-05-03 16:24:42] PM2 log: App name:APPid:0 online
[2018-05-03 16:24:42] PM2 error: Change detected on path pids\APP-0.pid for app APP- restarting
```

This will go on forever, visual inspection shows the pid file for APP being destroyed and recreated. If I run `pm2 stop` on this, followed by `pm2 start`, it will run OK, but restarting the service will not work correctly.

Have you seen this before?

Thanks.

**Comment by DaveMacNeil** [comment]
OK, I've found that doing the `pm2 save` will create the endless loop, and if you `pm2 stop` and `pm2 start`, it will still have this endless loop on service restart, but if you do `pm2 save` again after it is stable from the restart, it will be OK on server restart.

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
