### ISSUE TITLE
windows server 2016 standart - keepping node.exe proccesses

### ISSUE THREAD

**Issue by sagitsofan** [jon-hall/pm2-windows-service#44]
While using this module in windows server 2016, stopping the PM2 window service, multiples "node.exe" process are still exists and not disapears..
i added force killing while stopping the service.
needs to create branch permmision..

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
