### ISSUE TITLE
Occasional failure to start service with system reboot

### ISSUE THREAD

**Issue by spemmons** [jon-hall/pm2-windows-service#48]
I am using this service on about 90 machines with varying version of Windows and sometimes on system reboots, the PM2 service doesn't start.

I have not found any errors logged in either the PM2 logs or Windows Event Viewer that suggests any cause. In fact, I was surprised to find that there is NO entry of success of fail for the PM2 service in the Windows Event Viewer either way.

I'm suspecting some kind of race condition where PM2 needs something to be running that isn't yet, but don't know what that might be.

Any suggestions?

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
