### ISSUE TITLE
Log on Privileges

### ISSUE THREAD

**Issue by JLuboff** [jon-hall/pm2-windows-service#49]
This is more of a potential caveat then an issue. I have found an issue when using this module that on restart, while my app is running, I could not access network storage (used to store files for upload/download as opposed to directly on the server). I was getting `EPERM: operation not permitted`. After pulling my hair out for a while, testing different project folders, etc. I realized that the service runs as "Local System", which by definition only has local privileges. My understanding is that you can assign permissions to the computer account and that would give "Local System" the corresponding permissions on the network storage but I did not have any luck. I had to change the log on to a domain admin (theoretically this could be a domain user with permissions as well) and change under Recovery for First failure to Restart the Service.  
Not sure if this is something worth while to post in the caveat section or if there is a better solution than what I've presented.

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
