### ISSUE TITLE
If the user initiating the service signs out, PM2 stops

### ISSUE THREAD

**Issue by spemmons** [jon-hall/pm2-windows-service#5]
I've installed this module AND I had to explicitly install PM2 globally as documented, but if I sign out as the admin user, PM2 is stopped.

Maybe I'm doing something wrong?

**Comment by spemmons** [comment]
I've checked the system logs and I get the following error that seems to occur after I terminate the Windows Power Shell used to run PM2:

Child process [9980 - C:\Program Files\nodejs\node.exe --harmony "C:\Users\arenaadmin\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\node-windows\lib\wrapper.js" -f "C:\Users\arenaadmin\AppData\Roaming\npm\node_modules\pm2-windows-service\src\service.js" -l "PM2" -g 0.25 -w 1 -r 3 -a n] terminated with 0

**Comment by spemmons** [comment]
I checked in the daemon log for pm2-windows-service and see the following error:

fs.js:794
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'C:\etc.pm2'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Object.CLI.pm2Init (C:\Users\semmons\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\CLI.js:39:8)
    at Object.<anonymous> (C:\Users\semmons\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\index.js:9:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by spemmons** [comment]
I created the "c:\etc" directory and now I get an error saying that there is no dump file.

the .pm2 directory is created in my user's home directory, but the service expects it (now) at "C:\etc.pm2".

I'm looking for how to tell PM2 to save the dump file there, but not finding it...

**Comment by jon-hall** [comment]
Thanks for posting the issue and including as much details as you have - apologies I didn't get back to you sooner.

I think just running `pm2 dump` should create the dump file, though it shouldn't be necessary to have one to start the service.  If you could put up a stack trace/logs for the missing dump file error I'll take a look at why it's not working as expected as soon as I can.

With regards to it using `C:\etc.pm2` as the home directory - make sure you have `PM2_HOME` set to `C:\.pm2` (or your preferred home directory) as a **machine-level** environment variable if you want to change that (as per the caveats, this should be a directory which is accessible to the service user for read and write).

**Comment by spemmons** [comment]
OK, the problem seemed to stem from the fact that the PM2_HOME variable was not set and needed to be set at the machine level (setx /m ...).

I'll call this complete.

**Comment by s-a** [comment]
@spemmons I have the same problem on my server. To which directory did you set the `PM2_HOME` `c:\.pm2`? We tried this but still get the error message from your comment at https://github.com/jon-hall/pm2-windows-service/issues/5#issuecomment-221131299

**Comment by jon-hall** [comment]
@s-a The first thing to check is that `PM2_HOME` is set at machine-level (e.g. using `SETX /m PM2_HOME C:\.pm2`), and that the folder specified is accessible for read and write to the user the service is running under (`SYSTEM` by default).

If neither of those is the cause, could you post up the error log you're getting and I'll try and figure out what else might be going wrong, thanks.

**Comment by s-a** [comment]
Thanks for response. It works after I set the env var value to `c:\Users\<username>\.pm2\`. Seems https://github.com/jon-hall/pm2-windows-service/issues/8 is my next stumbling stone
