### ISSUE TITLE
Trying to install - Hangs after answering "Perform environment setup (recommended?"

### ISSUE THREAD

**Issue by NeoMatrixJR** [jon-hall/pm2-windows-service#51]
I'm trying to set this up but it just hangs after answering this...either yes or no.

**Comment by jmmoser** [comment]
@NeoMatrixJR I experienced the same issue running Node v10.12.0 on Windows Server 2016.  The pm2-service-install command worked after downgrading to Node v8.12.0.

**Comment by WynterFoxx** [comment]
@jmmoser That fixed it for me too.

**Comment by NeoMatrixJR** [comment]
That got it, thanks!

**Comment by tbadlov** [comment]
Are there any plans to correct this to use the LTS version of Node?

**Comment by eMuonTau** [comment]
I think it is because of old Inquirer version. After upgrading it to 5.0 or newer solved the problem for me.

**Comment by aimerib** [comment]
> I think it is because of old Inquirer version. After upgrading it to 5.0 or newer solved the problem for me.

You were spot on! Upgrading inquirer to newest version fixed this for me.

Updating the dependency for a module was new territory to me. I cannot recommend this method to anyone else struggling with the same issue, but what I did to get it going was:

```bash
npm install -g npm-check-updates

cd %USERPROFILE%\AppData\Roaming\npm\node_modules\pm2-windows-service
ncu inquirer -u
npm install
```

I ended up piecing this together from reading this article: [https://flaviocopes.com/update-npm-dependencies/](https://flaviocopes.com/update-npm-dependencies/)
and further reading the npm page for npm-check-updates: [https://www.npmjs.com/package/npm-check-updates](https://www.npmjs.com/package/npm-check-updates)

**Comment by shilezi** [comment]
> > I think it is because of old Inquirer version. After upgrading it to 5.0 or newer solved the problem for me.
> 
> You were spot on! Upgrading inquirer to newest version fixed this for me.
> 
> Updating the dependency for a module was new territory to me. I cannot recommend this method to anyone else struggling with the same issue, but what I did to get it going was:
> 
> ```shell
> npm install -g npm-check-updates
> 
> cd %USERPROFILE%\AppData\Roaming\npm\node_modules\pm2-windows-service
> ncu inquirer -u
> npm install
> ```
> 
> I ended up piecing this together from reading this article: https://flaviocopes.com/update-npm-dependencies/
> and further reading the npm page for npm-check-updates: https://www.npmjs.com/package/npm-check-updates

This fixed it for me as well. 
Thanks.

**Comment by af-vanwykgav** [comment]
> > > I think it is because of old Inquirer version. After upgrading it to 5.0 or newer solved the problem for me.
> > 
> > 
> > You were spot on! Upgrading inquirer to newest version fixed this for me.
> > Updating the dependency for a module was new territory to me. I cannot recommend this method to anyone else struggling with the same issue, but what I did to get it going was:
> > ```shell
> > npm install -g npm-check-updates
> > 
> > cd %USERPROFILE%\AppData\Roaming\npm\node_modules\pm2-windows-service
> > ncu inquirer -u
> > npm install
> > ```
> > 
> > 
> > I ended up piecing this together from reading this article: https://flaviocopes.com/update-npm-dependencies/
> > and further reading the npm page for npm-check-updates: https://www.npmjs.com/package/npm-check-updates
> 
> This fixed it for me as well.
> Thanks.

This did not fix it for me.   

The command below still hangs (and prompts for input):

`pm2-service-install -n "my service name" --unattended`

I went further to try:

```
cd %USERPROFILE%\AppData\Roaming\npm\node_modules\pm2-windows-service
ncu -u 
npm install 
```

Still no success. Any ideas?

ps. Windows 10 and server 2016

**Comment by deepforu47** [comment]
Getting same issue. 

> pm2-service-install -n "my service name" -

above command hangs.

**Comment by kmcgurty** [comment]
> cd %USERPROFILE%\AppData\Roaming\npm\node_modules\pm2-windows-service

It's worth mentioning, my folder was installed inside `C:\Program Files\nodejs\node_modules\pm2-windows-service`. Dunno why - might help someone in the future.

**Comment by PsyTae** [comment]
worked for me!

**Comment by kieselai** [comment]
@jon-hall Would you be open to adding someone as an admin for this project so updates can be pushed?

**Comment by vchabal** [comment]
The problem is that `node_modules/pm2-windows-service/package.json` has incompatible dependency version of `inquirer`. Command `ncu inquirer -u` updated inquirer to version `^7.3.3` which fixes the problem.

To help others with understanding of this issue, i'm including part of my configuration. See `init` script.
As well I recommend you to read [stackoverflow answer](https://stackoverflow.com/questions/42758985/windows-auto-start-pm2-and-node-apps#answer-42770772) to configure the pm2 service.

```
  "devDependencies": {
    "npm-check-updates": "^10.2.5",
    "pm2-windows-service": "^0.2.1"
  },
  "scripts": {
    "init": "npm install && npm run ncu-pm2 && npm run create",
    "create": "pm2-service-install -n pm2-service",
    "ncu-pm2": "cd node_modules/pm2-windows-service && ncu inquirer -u && cd ../.. && npm install"
  },
```
