### ISSUE TITLE
Installing without prompts?

### ISSUE THREAD

**Issue by IPWright83** [jon-hall/pm2-windows-service#54]
I'm trying to use `pm2-windows-service` to install multiple services (in our case we want them to be discrete rather than pm2 centrally running/managing them all together) as part of a deployment script.

At the moment though, I'm not sure how I avoid the on-screen prompts during the installation process? Is there a way I can provide the parameters up-front/setup environment variables so we don't need respond via the command line questions?

**Comment by josh-green** [comment]
It looks like this feature has been [implemented in the `pm2-service-install` cmd](https://github.com/jon-hall/pm2-windows-service/blob/master/bin/pm2-service-install#L8), but there hasn't been a release of the code as of latest (0.2.1) on the npm registry.
@jon-hall could this be arranged?

**Comment by josh-green** [comment]
This is already raised in #37, so this issue can be closed.
