### ISSUE TITLE
Windows 10 installation locks up and does not complete

### ISSUE THREAD

**Issue by spemmons** [jon-hall/pm2-windows-service#55]
I've used this service on many versions of Windows successfully, but am stuck trying to install on a new VM using Windows 10. I wish I had more details and can try to answer any diagnostic questions, but that's all I know right now. Any suggestions?

**Comment by dankell** [comment]
We're having the same issue on Windows Server 2016. Hit install, answer yes and it hangs up. Give it 15 minutes ctrl-c and nothing is registered in Services. 

I have had some luck with saying "no" on the first question. Again it seems to hang, but does seem to install a service once it's interrupted.

**Comment by jotamorais** [comment]
I'm experiencing the same issue in different machines (work and personal).
I got it working when with Node v9.8.0 and NPM v5.6.0: 
![image](https://user-images.githubusercontent.com/5201388/52582805-afb9c100-2df3-11e9-9f12-510c75fabfda.png)


But once I upgrade Node to latest v11.9.0 with NPM 6.5.0, I start having the same problem - pm2-service-install hangs in the first prompt:
![image](https://user-images.githubusercontent.com/5201388/52582929-f9a2a700-2df3-11e9-9549-25375199d6d9.png)


It seems to be some incompatibility with Node's latest version.
Does anyone have any idea what it could be?

**Comment by c2digital** [comment]
I found the solution in https://github.com/jon-hall/pm2-windows-service/issues/51 solved it for me (Inquirer dependency needed updating) - would that help you?

**Comment by dankell** [comment]
> I found the solution in #51 solved it for me (Inquirer dependency needed updating) - would that help you?

That seems to skip the issue I was finding. Will need to do some testing to see if I can get it actually working ;)

**Comment by alabastida** [comment]
The solution worked fine for my Windows 10 dev machine, but not on Windows Server 2016., after doing the inquirer update it still fails for me getting stuck at "Perform environment setup (recommended)? Yes"

**Comment by spidgorny** [comment]
Downgrading to Node 9 helped me as well.
Now I can answer to all of the questions.

**Comment by sangimed** [comment]
> 
> 
> The solution worked fine for my Windows 10 dev machine, but not on Windows Server 2016., after doing the inquirer update it still fails for me getting stuck at "Perform environment setup (recommended)? Yes"

EDIT : A possible solution https://adamtuttle.codes/blog/2019/node-apps-as-windows-services/
Same on my machine (`nodejs 12.16.1 LTS` + `Win 10 Professional 17763.1039`)

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
