### ISSUE TITLE
pm2-service-install -n PM2-NEW-APP not working with Window Server 2019

### ISSUE THREAD

**Issue by abhishekhingu** [jon-hall/pm2-windows-service#56]
When I run this command. process get stuck after first step.
I am running this command on window server 2019

**Comment by Schokojim** [comment]
Hello abhishekhingu, got the same problem. Found an issue, which solved it (https://github.com/jon-hall/pm2-windows-service/issues/51):
# just install
npm install -g pm2-windows-service
# fix for win10/ server 2019
npm install -g npm-check-updates
cd %USERPROFILE%\AppData\Roaming\npm\node_modules\pm2-windows-service
ncu inquirer -u
npm install
# now u can
pm2-service-install -n PM2

**Comment by HobaiRiku** [comment]
I think  the inquirer should update in this repo, why not?
for who uses nvm, the global npm is not located at %USERPROFILE%\AppData\Roaming\npm.

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
