### ISSUE TITLE
"pm2 ls" show nothing after execute "pm2 kill" several(4-5) times.

### ISSUE THREAD

**Issue by simplast** [jon-hall/pm2-windows-service#59]
All my projects is online after i execute 'pm kill'  until i do it 4-5 times

**Comment by simplast** [comment]
Also i found the pm2 service has been stopped

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
