### ISSUE TITLE
Custom service name support

### ISSUE THREAD

**Issue by letalumil** [jon-hall/pm2-windows-service#6]
Is it possible to specify the service name during the `pm2-service-install` command execution? I see that install function [takes](https://github.com/jon-hall/pm2-windows-service/blob/master/src/install.js#L15) name as a parameter, but don't know how to provide it via command line.

I'd like to have something like this:

``` cmd
pm2-service-install -name "My PM2 service"
```

If there is no such functionality, I can implement it via [minimist](https://github.com/substack/minimist) and make a PR.

**Comment by jon-hall** [comment]
Thanks for the suggestion, it should definitely allow this - not sure why I didn't make use of that parameter in the CLI; it should be a quick fix though so I'll get it added in as soon as possible.

**Comment by jon-hall** [comment]
Added into master, you can now supply the service name using either `-n` or `--name` when running `pm2-service-install`, will publish a new version soon but you can install from github (`npm install jon-hall/pm2-windows-service -g`) if you need the functionality before then.

**Comment by letalumil** [comment]
Awesome, thank you!
