### ISSUE TITLE
task scheduling to automate send email and start the pm2 services using powershell

### ISSUE THREAD

**Issue by Deepak-Agarwal-663** [jon-hall/pm2-windows-service#60]
I have created a website named **abccompany.com** and used a node js with pm2 services. now I want to make a task scheduled like that whenever my website goes down or services go offline it checks for pm2 status either it is **online** or **offline** in every **x seconds or minutes** and automatically sends an email to admin and automatically starts the services without admin interference so that there should not be any **fault tolerance** when anybody reached or viewed my website. So how to do all this in using **Power Shell** and **task scheduler**.

suppose I want to check whether my pm2 status is **online** or **offline** by typing pm2 status in **command prompt** as follows:

![image](https://user-images.githubusercontent.com/59562234/71814735-5b6e9e00-30a3-11ea-9186-ae70aff9f382.png)

now if instead of online if **offline** is showing then it should run PowerShell script in which it will send **email to an admin** and automatic **start the pm2 services** using the command "**pm2 resurrect**".

And I have PowerShell code of sending email file too but didn't get where and how to use and start it. You can find it below as :

**Code:**
`$secpasswd = ConvertTo-SecureString "your password" -AsPlainText -Force`
`$cred = New-Object System.Management.Automation.PSCredential ($username, $secpasswd)`

`#Send-MailMessage -Attachments "E:\Email Code.ps1" -From 'abc <abc@abccompany.in>' -To 'Dark Horse <xyz@abccompany.in>' -Cc 'Black Widow <def@abccompany.in>' -Bcc 'Iron Man <ghi@abccompany.in>' -Subject "Test Email from Powershell" -Credential $cred -SmtpServer smtp.office365.com -Port 587 -UseSsl`

`$Username = "your username"`
`$Password = "your password"`

`$path = @(`
`"C:\Users\Admin\Desktop\file1.txt"`
`"C:\Users\Admin\Desktop\file2.txt"`
`)`

`function Send-ToEmail([string]$email, [array]$attachmentpath)`
`{`
`try`
`{`
    `$message = new-object Net.Mail.MailMessage;`
    `$message.From = "abc@abccompany.in";`
    `$message.To.Add($email);`
    `$message.Subject = "Email from Powershell";`
    `$message.IsBodyHtml = $true;`
    `#$message.Body = "<h1>Please find the Attachment</h1>";`

    `foreach ($file in $attachmentpath)`
   ` {`
     `$attachment = New-Object Net.Mail.Attachment($file);`
     `$message.Attachments.Add($attachment);`
    `}    `

   ` $smtp = new-object Net.Mail.SmtpClient("smtp.office365.com", "587");`
    `$smtp.EnableSSL = $true;`
    `$smtp.Credentials = New-Object System.Net.NetworkCredential($Username, $Password);`
    `$smtp.send($message);`
    `Write-Host "Mail Sent" ;`
    `$attachment.Dispose();`
 `}`

 `catch`
 `{`
  `  Write-Host "Error occured"`
` }`
`}`
`Send-ToEmail -email "toemail address" -attachmentpath $path;`

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
