### ISSUE TITLE
Running service as specific user

### ISSUE THREAD

**Issue by jainpradeep** [jon-hall/pm2-windows-service#64]
My node process acesses a network folder. Pm2-windows-service runs the node process but as it is running with administrator it can not acess the network folder. Can a daemon process run as a specific user?

**Comment by steffenstolze** [comment]
hmm.. install the pm2-windows-service under a user that has the necessary network access rights. then it will create a windows service. go to the windows services, select your service and [adjust the user ](https://www.microfocus.com/documentation/enterprise-developer/ed30/ESdotNET/GUID-00A022C3-2688-4B9D-8DA2-7CF4E828D5BA.html )

this is how i do it.

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
