### ISSUE TITLE
Warning about non-existent property & circular dependency

### ISSUE THREAD

**Issue by RayDeanTech** [jon-hall/pm2-windows-service#65]
This package _appears_ to successfully install and uninstall PM2 as a Windows Service; however, the install/uninstall commands both trigger about 2 dozen warnings (see screenshot):

`(node:7008) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency`

![image](https://user-images.githubusercontent.com/21373144/98374936-679ef100-200f-11eb-8453-503599e3dff4.png)

Windows Server, 2012 R2
npm:  6.14.8
node:  14.15.0

**Comment by rconstantine** [comment]
same here. Node 16.14.0 and Yarn something

**Comment by TomMiller-mas** [comment]
I am getting it too.

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
