### ISSUE TITLE
Project maintained?

### ISSUE THREAD

**Issue by xinthose** [jon-hall/pm2-windows-service#67]
Hello.  By the looks of it, this project is not maintained anymore by @jon-hall.

**Comment by TomMiller-mas** [comment]
It doesn't look like it.  @jon-hall would you consider adding another contributor so we can process some of these check-ins? Would be willing to work on some of this stuff if I thought there was a chance that it would get reviewed and checked into the code base.

**Comment by xinthose** [comment]
I use [`pm2-installer`](https://github.com/jessety/pm2-installer) now.

**Comment by TomMiller-mas** [comment]
Just found it myself.  It looks good and about to try it out.
