### ISSUE TITLE
pm2 service resurrect error

### ISSUE THREAD

**Issue by firattaskin** [jon-hall/pm2-windows-service#70]
My error text on "pm2-windows-service\src\daemon\pm2.err.log":
Error: Script not found: C:\Windows\system32\pm2 resurrect

ENV:
PM2_SERVICE_SCRIPTS=pm2 resurrect

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
